#!/bin/sh

set -e

# install homebrew
if [ ! -f /opt/homebrew/bin/brew ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -d ~/dotfiles ]; then
  cd ~
  git clone https://github.com/matatabiii/dotfiles.git
fi

brew bundle -v --file=~/dotfiles/Brewfile

if [ ! -d ~/.config ]; then
  mkdir ~/.config
fi

stow -v -d ~/dotfiles/packages -t ~ zsh starship
